bifrost-vui/bifrost-front-end-library

- .editorconfig
newlines = false
indent-size = 2 for twig & html files
> editor-config  update :

- CHANGELOG.mdx
- projects/front-end-library/src/lib/components/tab/scss/index.scss
- projects/front-end-library/src/lib/scss/base/_base.scss
- projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
- position of the horizontal scrollbar
- position of the gradiant
- removed unecessary css (created in the previous verion)
note : needs testing with real devices
> DS-193-Bug-tab-on-mobile

- projects/front-end-library/src/lib/components/card/scss/index.scss
> DS 196 - fix icon stretched in card

- CHANGELOG.mdx
- projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
- projects/front-end-library/src/lib/components/badge/scss/index.scss
- projects/front-end-library/src/lib/components/badge/twig/index.twig
- projects/front-end-library/src/lib/components/card/scss/index.scss
Note :
pour les badges avec angle,  `text-overflow : ellipis` a besoin d'une taille fixe (px ou rem) pour fonctionner - la valeur que j'ai mise est ouverte pour discussion mais on pourrait peut-être l'ajouter en option dans une version subséquente si ça devient un enjeux
> DS-221 - Badge is Multiline

- projects/front-end-library/src/lib/components/carousel/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/carousel/scss/index.scss
**Carousel != Slideshow**
Je précise car je me suis emmêlé les pinceaux :)
> ds-208-fix item's height in carousel

- projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
- projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
Cette PR n'est pas une priorité, on peux se la garder pour un autre fois. 
Par contre, elle contient des ajustements qui peuvent être intéressant à lire pour les prochaines PR.
> ds-315 improve banner advanced

- CHANGELOG.mdx
- projects/front-end-library/src/lib/components/logo/scss/index.scss
- projects/front-end-library/src/lib/components/logo/twig/index.twig
- projects/front-end-library/src/lib/components/navigation-header/scss/index.scss
- projects/front-end-library/src/lib/components/navigation-header/twig/index.twig
testé aussi sur le safari 12 qui causait problème dans la version précédente de la branche.
je crois que le problème aurait probablement été visible sur tous les Safari en mode desktop puisque je ne pouvais tester que mobile.PTI - Il me reste 17 minutes de test sur mon 7 jours de free trial - j'espère ne pas en avoir besoin
> DS-312 - fixed height logo with breakpoints

- CHANGELOG.mdx
- projects/front-end-library/src/lib/components/tab/scss/index.scss
[see tab here](https://bifrost-front-end-library-git-ds-331-tab-ful-8233ba-bifrost-vui.vercel.app/?path=/story/components-tab--drupal)
intervention minimale  : juste ce fix là + retrait de sauts de lignes dans le CSS et ordre de certaines propriétés pour harmoniser avec nos standards 
testé  : FFox Chrome Edge - n'a aucun impact sur mobile
> DS-331 - Tab Full width bottom border

- .storybook/preview.ts
J'en ai profité pour mettre a jour le fichier `preview.ts`
> ds-343 move UI Kit section at the bottom of the sidebar

- projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/input-radio/scss/index.scss
- projects/front-end-library/src/lib/components/input-radio/twig/index.twig
https://bifrost-front-end-library-git-ds-345-fix-che-a8a4e8-bifrost-vui.vercel.app/?path=/story/components-input-radio--drupal
Pas capable de reproduire le bug de mon côté. Valider que ça règle le problème svp.
> DS-345 - fix radio button - make it crossbrowser

- CHANGELOG.mdx
- projects/front-end-library/src/lib/components/input-checkbox-option/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/input-checkbox-option/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/input-checkbox-option/angular/input-checkbox-option.component.html
- projects/front-end-library/src/lib/components/input-checkbox-option/angular/input-checkbox-option.component.ts
- projects/front-end-library/src/lib/components/input-checkbox-option/angular/input-checkbox-option.module.ts
- projects/front-end-library/src/lib/components/input-checkbox-option/scss/index.scss
- projects/front-end-library/src/lib/components/input-checkbox-option/twig/index.twig
- projects/front-end-library/src/lib/components/input-radio-option/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/input-radio-option/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/input-radio-option/angular/input-radio-option.component.html
- projects/front-end-library/src/lib/components/input-radio-option/angular/input-radio-option.component.ts
- projects/front-end-library/src/lib/components/input-radio-option/angular/input-radio-option.module.ts
- projects/front-end-library/src/lib/components/input-radio-option/scss/index.scss
- projects/front-end-library/src/lib/components/input-radio-option/twig/index.twig
- projects/front-end-library/src/lib/scss/index.scss
This PR needs to be merge after [ds-333-rename-input-radio-and-input-checkbox](https://github.com/bifrost-vui/bifrost-front-end-library/tree/ds-333-rename-input-radio-and-input-checkbox).
> ds-333 patch

- CHANGELOG.mdx
- projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
Before:
Actual:
- Tested : hero, block selection, and all other components in normal and highlight state
> DS-277: fix de secondary button display on highlight

- .storybook/preview.ts
- CHANGELOG.mdx
- CONTRIBUTING.mdx
- e2e/app.e2e-spec.ts
- projects/front-end-library/src/lib.module.ts
- projects/front-end-library/src/lib/_doc/2-Implementation/4-drupal.stories.mdx
- projects/front-end-library/src/public-api.ts
- projects/front-end-library/src/test.ts
- projects/showcase-angular/src/environments/environment.ts
- protractor.conf.js
- webpack.config.js
missing stuff from https://github.com/bifrost-vui/bifrost-front-end-library/pull/358
> DS-388-storybook-65-from-server-express-removed

- CHANGELOG.mdx
- projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
- projects/front-end-library/src/lib/components/card/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/card/angular/card.component.ts
- projects/front-end-library/src/lib/components/card/twig/index.twig
Work on the base Card component
Look on the Plan Card
Look on the Phone Card (but story was not adjusted)
> DS-376: Set Card Title to be a object with 2 part

- projects/front-end-library/src/lib/components/carousel/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/carousel/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/carousel/scss/index.scss
- projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/js/components/slick-carousel.js
- projects/front-end-library/src/lib/js/demo/bifrost/carousel.js
- projects/front-end-library/src/lib/scss/_pattern-lab/vui-components/carousels/_carousel-mobility-phones.scss
- projects/front-end-library/src/lib/scss/dependencies/bifrost/_carousel.scss
- projects/front-end-library/src/lib/scss/dependencies/bootstrap/_bootstrap_variables.scss
Changes for this ticket : https://groupemedia.atlassian.net/browse/DS-385
> DS-385: carousel mobile display rendering

- projects/front-end-library/src/lib/components/banner/twig/index.twig
- projects/front-end-library/src/lib/components/card/twig/index.twig
- projects/front-end-library/src/lib/components/carousel/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/hero/twig/index.twig
- projects/front-end-library/src/lib/components/image-lazy-load/twig/index.twig
- projects/front-end-library/src/lib/components/row-button/twig/index.twig
- projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
- projects/front-end-library/src/lib/components/tile-post/twig/index.twig
- projects/front-end-library/src/lib/components/tile/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/tile/_doc/list.drupal.twig
Add `loading="lazy"` on all `<img>` as per this ticket : https://groupemedia.atlassian.net/browse/DWN-13753
> DS-457: Add loading="lazy" on all <img>

- projects/front-end-library/src/lib/components/card/_doc/api.stories.mdx
- projects/front-end-library/src/lib/components/card/_doc/data.ts
- projects/front-end-library/src/lib/components/card/angular/api.component.ts
- projects/front-end-library/src/lib/components/card/angular/api.model.ts
- projects/front-end-library/src/lib/components/card/angular/card.component.ts
- projects/front-end-library/src/lib/components/card/scss/index.scss
- projects/front-end-library/src/lib/components/card/twig/index.twig
- projects/front-end-library/src/lib/components/channels/angular/channels.component.ts
- projects/front-end-library/src/lib/components/channels/scss/index.scss
- projects/front-end-library/src/lib/components/modal/twig/index.twig
- projects/front-end-library/src/lib/components/tab/_doc/api.stories.mdx
- projects/front-end-library/src/lib/components/tab/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/tab/_doc/real-tab-template.drupal.twig
- projects/front-end-library/src/lib/components/tab/angular/api.component.ts
- projects/front-end-library/src/lib/components/tab/angular/api.model.ts
- projects/front-end-library/src/lib/components/tab/angular/tab.component.ts
- projects/front-end-library/src/lib/components/tab/js/index.js
- projects/front-end-library/src/lib/components/tab/scss/index.scss
- projects/front-end-library/src/lib/components/tab/twig/index.twig
- projects/front-end-library/src/lib/components/tab/twig/real-tab.twig
- projects/front-end-library/src/lib/js/bifrost-components.js
- projects/front-end-library/src/lib/scss/dependencies/bifrost/_font-size.scss
- projects/front-end-library/src/lib/scss/dependencies/bootstrap/overwrite/_modal.scss
- projects/front-end-library/src/lib/scss/index.scss
- projects/front-end-library/src/lib/scss/themes/_index.scss
- projects/front-end-library/src/lib/scss/themes/videotron/_font-size.scss
> DS-478 - Card link and channels modal

- projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
- projects/front-end-library/src/lib/components/block-highlight/_doc/api.stories.mdx
- projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/block-highlight/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/block-highlight/angular/api.component.ts
- projects/front-end-library/src/lib/components/block-highlight/angular/api.model.ts
- projects/front-end-library/src/lib/components/block-highlight/angular/block-highlight.component.ts
- projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
- projects/front-end-library/src/lib/components/button/angular/api.model.ts
- projects/front-end-library/src/lib/components/button/angular/button.component.ts
- projects/front-end-library/src/lib/components/card/angular/card.component.ts
- projects/front-end-library/src/lib/components/hero/angular/hero.component.ts
See `Block Highlight` component : https://bifrost-front-end-library-git-feature-ds-505-ed48ca-bifrost-vui.vercel.app/?path=/story/components-block-highlight--drupal
- Adjust documentation
- Add internal API documentation page
- Change `reversed` prop to `isReversed`
- Change `paragraph` type from "string" to `HTMLElement`
- Add `isContentCentered` prop to center vertically the content
- Add `buttonHierarchy` prop to choose a style for the button
> Feature - DS-505 - Block Highlight center content, rich text, button hierarchy

- .vscode/settings.json
- projects/front-end-library/src/lib/components/good-to-know/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/good-to-know/_doc/template.angular.component.html
- projects/front-end-library/src/lib/components/good-to-know/_doc/template.angular.component.ts
- projects/front-end-library/src/lib/components/good-to-know/_doc/template.angular.module.ts
- projects/front-end-library/src/lib/components/good-to-know/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/good-to-know/angular/good-to-know.component.html
- projects/front-end-library/src/lib/components/good-to-know/angular/good-to-know.component.ts
- projects/front-end-library/src/lib/components/good-to-know/angular/good-to-know.module.ts
- projects/front-end-library/src/lib/components/good-to-know/scss/index.scss
- projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
- projects/front-end-library/src/lib/scss/index.scss
Intégration de la bannière Good to know afin d'améliorer son affichage mobile
Résultat en desktop voulu : https://videotron.com/node/7286/layout
Résultat en mobile: blob:https://groupemedia.atlassian.net/753348ba-0534-4ad3-9342-9532ffcdad83#media-blob-url=true&id=c2f859b6-2b72-4b0a-8986-2f1a1af73aa5&contextId=1491466&collection=
(impossible d'afficher des images ici de mon bord)
> DS-438 | new | Good to know banner

- projects/front-end-library/src/lib/components/chip/angular/api.model.ts
- projects/front-end-library/src/lib/components/chip/angular/chip.component.ts
- projects/front-end-library/src/lib/components/chips-group/_doc/data.ts
- projects/front-end-library/src/lib/components/chips-group/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/chips-group/_doc/template.angular.component.html
- projects/front-end-library/src/lib/components/chips-group/_doc/template.angular.component.ts
- projects/front-end-library/src/lib/components/chips-group/_doc/template.angular.module.ts
- projects/front-end-library/src/lib/components/chips-group/_doc/template.drupal.twig
- projects/front-end-library/src/lib/components/chips-group/angular/chips-group.component.html
- projects/front-end-library/src/lib/components/chips-group/angular/chips-group.component.ts
- projects/front-end-library/src/lib/components/chips-group/angular/chips-group.module.ts
- projects/front-end-library/src/lib/components/chips-group/scss/index.scss
- projects/front-end-library/src/lib/components/chips-group/twig/index.twig
- projects/front-end-library/src/lib/scss/index.scss
See the component on Storybook : https://bifrost-front-end-library-git-feature-ds-526-e333a8-bifrost-vui.vercel.app/?path=/story/components-chips-group--drupal
- Add a `IChip` interface to `Chip` component
- Develop the new component
- Documentation of the component
> Feature - DS-526 - Create chips group component

- projects/front-end-library/src/lib/sections/plp/js/index.js
- Fix component JavaScript execution when it is not present in the loaded webpage. For the code to be executed, the component MUST be present in the loaded page.
> Bugfix - DS-542 - Fix PLP JavaScript bug

- projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
- projects/front-end-library/src/lib/components/card/_doc/template.group.drupal.twig
- projects/front-end-library/src/lib/components/card/scss/index.scss
- Fix card by adding missing CSS styles on class `.bf-card__container`
> Bugfix - DS-543 - Fix card price zone alignment
